### ISSUE TITLE
アクション「ユートピア」の動作の単位を1文字ごとではなく1音節ごとにしてほしい

### ISSUE THREAD

**Issue by bee7813993** [shinta0806/NicoKaraMaker2#131]
いつも開発ありがとうございます。ゆーふうりんです。

アクション「ユートピア」について
リードインおよび文字が消えていく動作は、1文字単位でもいいかと思うのですが、
ワイプ中の文字が膨らむ動作を1文字ごとから1音節ごとにしてほしいです。

日本語はたいてい1文字は1音節なのですが、英語などは複数文字で1音節となります。

two → 3文字で1音節
beautiful → beau / ti /ful (ビュー/ティ/フル)
far away → fa / r a / way （ファー/ ラ / ウェー )

1音節が分かれて膨らむと、歌っているときに違和感を感じてしまうので、まとめてほしいのです。

音節の検出はタグのある単位となります。
Don't worry → [00:37:57]Don't [00:37:86]wo[00:38:29]rry[00:38:68]

**Comment by shinta0806** [comment]
［対応状況］完了
［報告経路］コンタクト

**Comment by shinta0806** [comment]
RhythmicaLyrics と組み合わせて音節毎にルビを振れるようになったため、本件クローズします。
