### ISSUE TITLE
スペースが全部同じ幅になる

### ISSUE THREAD

**Issue by nikokara2020** [shinta0806/NicoKaraMaker2#178]
半角スペース、全角スペースが同じ幅になります。また、プロポーショナルフォントで半角カタカナの「ｦ」を1/4スペースに変えてる物も同じ幅になります。

**Comment by shinta0806** [comment]
開発者環境（Ver 8.29）にて確認してみたのですが、メイリオなどいくつかのフォントで確認したところ、半角スペースと全角スペースの幅は異なっていました。
![zenhan](https://user-images.githubusercontent.com/7196473/95669927-8f419b80-0bc0-11eb-9a12-dce2238ffe8a.png)

ご使用のニコカラメーカー 2 のバージョンとフォントを教えてください。

**Comment by nikokara2020** [comment]
ご対応ありがとうございます！読み込みの時点で反映がこうなる様です。旧ニコカラメーカーでは大丈夫なんですが。。。バージョンは8.29になります。お手数おかけ致します。

**Comment by shinta0806** [comment]
nikokara2020 さんの仰る「反映がこうなる」というのは、上で私が貼った写真のようになるということでしょうか。
上の写真では、全角スペースの幅のほうが半角スペースの幅よりも広くなっており、正常な動作となっています。
もし、全角スペースと半角スペースの幅が一緒になってしまうフォントがありましたらご教示ください。

**Comment by nikokara2020** [comment]
歌詞編集画面を添付してました。
上の1行は半角スペース。下の1行は全角スペースになります。
メモ帳の様な文字を打つ画面上で半角ですが、紺色に出てる歌詞は全部全角になっております。今一度画像を添付しますので、ご閲覧願います。

**Comment by shinta0806** [comment]
残念ながらこちらからは添付していただいた画像が見えません。
画像をブラウザに D&D すると、画像ファイル名がコメント欄に入るのですが、それは入っていますでしょうか。

**Comment by nikokara2020** [comment]
申し訳ございません。幅はやっぱり変化ありました。
ただ、旧ニコカラメーカーがプロポーショナルフォントで半角スペースがより小さい扱いになってたのが良かったです。
今回のニコカラメーカー2では、より厳正な幅になる様になってると思われます。

**Comment by shinta0806** [comment]
半角スペースよりもさらに小さなスペースを空けたいとのことですので、任意の幅のスペースを空ける方法をヘルプにまとめましたので、ご覧ください。
http://shinta.coresv.com/help/NicoKaraMaker2_JPN.html#NininoSpace

**Comment by nikokara2020** [comment]
こと細かにご対応頂き感謝いたします。
ありがとうございました。

**Comment by shinta0806** [comment]
お気持ちは嬉しいのですが、ツール類につきましては、必要に応じて公式より DL いたしますので、上記コメントからは削除お願いします。

**Comment by shinta0806** [comment]
以上により本件クローズします。
