### ISSUE TITLE
「歌詞編集」のショートカットキー等

### ISSUE THREAD

**Issue by aiueo1234aiueo** [shinta0806/NicoKaraMaker2#218]
開発ありがとうございます。
要望の出し方がこれで合っているのか分からないので、もし間違っていた場合はご教示頂ければと思います。
要望は以下の通りです。既出かどうかを検索し、確認しました。

1.歌詞編集タブでの「歌詞編集」のショートカットキー（ホットキー）追加

2.プレビュータブでの巻き戻し、早送りのショートカットキー追加

3.プレビュータブでの警告表示欄から該当箇所へのジャンプ

**Comment by shinta0806** [comment]
要望はこちらへ書き込んで頂いて問題ありません。

［対応状況］完了
［報告経路］コンタクト

**Comment by aiueo1234aiueo** [comment]
承知しました。
丁寧な対応ありがとうございます。

**Comment by shinta0806** [comment]
2 について、Ver 12.40 にて対応完了しました。

**Comment by shinta0806** [comment]
1 について、Ver 12.41 にて対応完了しました。

**Comment by shinta0806** [comment]
3 については #225 で管理します。

**Comment by shinta0806** [comment]
本件クローズします。
