### ISSUE TITLE
動画を読み込まない

### ISSUE THREAD

**Issue by nikokara2020** [shinta0806/NicoKaraMaker2#224]
無圧縮AVIを含む動画が全て読み込まれなくなりました。
https://shinta0806be.ldblog.jp/archives/9969533.html
も参照して試みましたが、無理でした。

**Comment by nikokara2020** [comment]
すみません。「Shark007コーデック」を削除したら直りました。

**Comment by nikokara2020** [comment]
違いました。Windows 10なんですが、UIのフォントをコマンドやレジストリエディタなどでカスタマイズして、回復オプションからの再起動からの青い画面が「□□□」で文字が表示され、結局カスタマイズを失敗したのが原因だったと思います。多分ファイルの読み込みでファイル名の文字コードの認識がおかしくなったものと思われます。こちらのソフトからするとファイル名が「□□□・・」みたいな状態になったんですね。お騒がせしました。

**Comment by shinta0806** [comment]
解決して何よりでした。

なお、最初に貼って頂いたリンクは初代ニコカラメーカー用の対応策で、ニコカラメーカー 2 では効果がありません。ニコカラメーカー 2 では、初期状態で一定の mp4 が読み込めるようになっており、正常に動作しているかどうかは、付属しているサンプル動画を読み込めるかどうかで確認することができます。
