### ISSUE TITLE
プレビュータブで開く警告一覧からの歌詞編集へのジャンプ

### ISSUE THREAD

**Issue by lato03** [shinta0806/NicoKaraMaker2#225]
プレビュータブで警告一覧を開き「歌詞編集のメイン、n行目の表示終了が歌唱終了より早くなっています。」と表示されている行をダブルクリックすると、歌詞編集画面の該当行にジャンプして欲しい。

**Comment by shinta0806** [comment]
ニコカラメーカー 3 にて管理します。
https://github.com/shinta0806/NicoKaraMaker3/issues/34
