### ISSUE TITLE
「既存プロジェクトの設定を適用」で既存プロジェクトを選択するとエラーが出る場合がある

### ISSUE THREAD

**Issue by lato03** [shinta0806/NicoKaraMaker2#227]
「既存プロジェクトの設定を適用」ボタンを押下し、特定のプロジェクトを選択した場合、以下のようなエラーが出る場合があります。
![image](https://user-images.githubusercontent.com/12814945/131371432-0dcf7645-8bf5-4e76-bb4c-cb0ee19cd92c.png)
但し、エラーが出た後に、再度「既存プロジェクトの設定を適用」ボタンを押下し、同じプロジェクトを選択するとエラーは発生せずに設定は正常に読み込まれているように見えます。
その代わり、それで作成したプロジェクトを、新規プロジェクト作成時に、「既存プロジェクトの設定を適用」で呼び出して設定すると、同じエラーが発生します。

**Comment by shinta0806** [comment]
［対応状況］見送
［報告経路］コンタクト

**Comment by shinta0806** [comment]
ニコカラメーカー 3 をリリースしたため本件クローズします。
