### ISSUE TITLE
動画出力とルビの記憶

### ISSUE THREAD

**Issue by nikokara2020** [shinta0806/NicoKaraMaker2#287]
ハードウェアエンコードに対応した圧縮コーデックの実装と、このソフトでルビを編集した後に該当の歌詞ファイルを外部ソフトで編集して上書きした後もルビをキープして欲しいです。

**Comment by shinta0806** [comment]
リクエストありがとうございます。

エンコードについては #159  にて管理します。

外部ソフトでの編集の結果については当該外部ソフトによるものなので、こちらでは対象外となります。

なお、ルビの編集は、ヘルプ（ https://shinta.coresv.com/help/NicoKaraMaker2_JPN.html#RubyhensyuuWindow ）に記載の通り、RhythmicaLyrics で行うことを推奨しています。

RhythmicaLyrics で編集したルビをニコカラメーカー 2 で読み込むことが可能です。詳細はヘルプ（ https://shinta.coresv.com/help/NicoKaraMaker2_JPN.html#KashiniRubywoFuruRhythmicaLyrics ）を参照してください。

［対応状況］完了
［報告経路］コンタクト
