### ISSUE TITLE
再生中のシークで応答不能

### ISSUE THREAD

**Issue by nikokara2020** [shinta0806/NicoKaraMaker2#306]
プレビューで字幕入りの動画を再生中にシークや秒送り秒戻しをすると曲が終るまで応答不能になります。(Windows 11)

**Comment by shinta0806** [comment]
［対応状況］完了
［報告経路］コンタクト
［関連チケット］#318

**Comment by shinta0806** [comment]
Ver 12.85 にて対応完了しました。
