### ISSUE TITLE
プレビュー時に応答なしになる。

### ISSUE THREAD

**Issue by anmoti** [shinta0806/NicoKaraMaker2#318]
## 現象
プレビュー時に再生バーの部分をクリックすると応答なしになる。

**Comment by anmoti** [comment]
https://d.kuku.lu/c7f68nuw4

**Comment by shinta0806** [comment]
［対応状況］完了
［報告経路］コンタクト

**Comment by shinta0806** [comment]
（メモ）

◆環境によって発生するしないが異なる模様。
発生しない：開発者メイン環境
発生する：VM10、VM11

◆発生する環境では、サンプル動画で早送りを連打すると発生する。
動画が最後まで再生を終えると応答が戻る。

◆報告は Ver 12.53 以降。
発生する環境でも、少なくとも Ver11.99 の頃は発生していない。

◆発生する環境でもフレームワークを .NET 6 に戻すと発生しない。

**Comment by shinta0806** [comment]
Ver 12.85 にて対応完了しました。
