### ISSUE TITLE
スプラッシュウィンドウでフリーズする

### ISSUE THREAD

**Issue by shinta0806** [shinta0806/NicoKaraMaker2#32]
ニコカラメーカー 2 を起動すると、スプラッシュウィンドウが表示されたままフリーズします。

［対応状況］完了
［報告経路］コンタクト

**Comment by shinta0806** [comment]
（事例 1）
非常用ログの「スプラッシュウィンドウ進捗 02」記録後にフリーズ
https://pbs.twimg.com/media/EXqVKBMU4AAk0Cx?format=png
![log](https://user-images.githubusercontent.com/7196473/81502708-6ddf3980-931a-11ea-87c8-0d6e4e314af0.png)
OS は Windows 10

（所見）
ファイル名が短い形式になっているのは何か関係があるか？

**Comment by shinta0806** [comment]
（事例 2）
「スプラッシュウィンドウ進捗 07」記録後にフリーズ

**Comment by UltimateAmitieKaiNiC** [comment]
その後はフリーズ続け…

**Comment by UltimateAmitieKaiNiC** [comment]
2020/05/10,16:07:36,12392,N9836/M1,"----------"
2020/05/10,16:07:36,12392,N9836/M1,"C:\Users\ADMINI~1\AppData\Local\Temp\.net\NicoKaraMaker2\cf0rqftn.z4o\NicoKaraMaker2.dll"
2020/05/10,16:07:36,12392,N9836/M1,"スプラッシュウィンドウ進捗 01"
2020/05/10,16:07:36,12392,N9836/M1,"スプラッシュウィンドウ進捗 02"

**Comment by UltimateAmitieKaiNiC** [comment]
ソフトウェアが更新された後、開くとすぐに「動作を停止しました」というプロンプトが表示されます

**Comment by shinta0806** [comment]
（Ver 6.18 β の段階での整理）
・事例 1 は、フリーズから動作停止に状況が変わった。
・事例 2 は、バージョンアップにより問題解決した模様。

**Comment by shinta0806** [comment]
事例 2 のパターンのフリーズについて解決したためこちらはクローズします。
事例 1 は別症状となったため、
https://github.com/shinta0806/NicoKaraMaker2/issues/88
にて管理します。
