### ISSUE TITLE
support new time tag format

### ISSUE THREAD

**Issue by hundun000** [shinta0806/NicoKaraMaker2#321]
RhythmicaLyrics  can't run in my PC bucause its japanese file names became garbled. I find a tool [RhythmiKaRuTTE](https://github.com/Juna-Idler/RhythmiKaRuTTE) and its output time tag format is `[00:00.00]`. This format can use in NicoKaraMaker1, but can't use in NicoKaraMaker2. 

And [RhythmiKaRuTTE's issue](https://github.com/Juna-Idler/RhythmiKaRuTTE/issues/9) said:
> [00:00:00]は日本独自の古い形式
>「NicoKaraMaker2」に[00:00.00]の対応をお願いしたほうがいいんじゃないかな？

**Comment by shinta0806** [comment]
[00:00.00] 形式の .lrc ファイルは、[00:00:00] 形式の .lrc ファイルとは仕様が異なっているように見受けられます。

[00:00:00] 形式の .lrc ファイルは仕様が公開されている標準フォーマットで、仕様書が
http://hp.vector.co.jp/authors/VA023256/TimeTagDev.html
にあり、ニコカラメーカー 2 はこれに準拠しています。

[00:00.00] 形式の .lrc ファイルは SONY の独自フォーマットではないでしょうか。仕様書はどこかに公開されていますか？

**Comment by hundun000** [comment]
I find the way to run RhythmicaLyrics successfully. No longer need to support RhythmiKaRuTTE.
