### ISSUE TITLE
タイトルを動画の前に黒背景で挿入したい

### ISSUE THREAD

**Issue by chrono216** [shinta0806/NicoKaraMaker2#352]
JOYSOUNDの本人映像曲などで見られるような黒背景(もしくは任意の画像)にタイトルを表示してから曲が始まるといったようなのをニコカラメーカで出来たら個人的に便利だなと思い書き込みさせていただきました。

**Comment by shinta0806** [comment]
素材動画タブで、「背景色＋音声ファイルを素材として使用」もしくは「1 枚の画像ファイル＋音声ファイルを素材として使用」を選ぶことにより、黒背景や画像を背景としたものを作ることができます。
