### ISSUE TITLE
起動時に動作停止する

### ISSUE THREAD

**Issue by shinta0806** [shinta0806/NicoKaraMaker2#88]
ニコカラメーカー 2 を起動すると、スプラッシュウィンドウ表示後すぐに「動作を停止しました」というプロンプトが表示されます。

![EbkGU3dU0AA0mdw](https://user-images.githubusercontent.com/7196473/85936348-bb4c5000-b934-11ea-8299-2ef668d9372e.png)

OS：中国語 Windows 10 Ver 1709

［対応状況］保留
［報告経路］コンタクト

**Comment by UltimateAmitieKaiNiC** [comment]
スプラッシュウィンドウでフリーズするとすぐに「動作を停止しました」というプロンプトが表示されます。

**Comment by UltimateAmitieKaiNiC** [comment]
Win10 Version: 1709
Log: https://www.dropbox.com/s/y1wni2h8i0zv0dk/NicoKaraMaker2.log?dl=0

**Comment by shinta0806** [comment]
（所見）
ログ中のアドオンエラーは正常な動作。
環境取得が動作していない模様。
WMI またはレジストリ取得でつまづいている可能性あり。
OS が中国語だからなのか、OS バージョンが古いからか、その他の原因か、現時点では不明。
→1909 以降のバージョンでの動作確認依頼中。

**Comment by UltimateAmitieKaiNiC** [comment]
2020/06/28,13:13:01,10896,N12912/M1,NicoKaraMaker2,Status,"起動しました：ニコカラメーカー 2 Ver 6.18 β ===================="
2020/06/28,13:13:01,10896,N12912/M1,NicoKaraMaker2,Status,"プロセス動作モード：64"
2020/06/28,13:13:01,10896,N12912/M1,NicoKaraMaker2,Status,"DirectX の初期化をしています..."
2020/06/28,13:13:01,10896,N12912/M1,NicoKaraMaker2,Status,"DirectX の初期化が完了しました。"
2020/06/28,13:13:01,10896,N12912/M1,NicoKaraMaker2,Error,"アドオン設定読み込み時エラー：<br>Could not find file 'C:\Users\Administrator\AppData\Roaming\SHINTA\NicoKaraMaker2\AddOns\SHINTA.SeqLinesBreaker.config'."
2020/06/28,13:13:01,10896,N12912/M1,NicoKaraMaker2,Status,"　スタックトレース：<br>   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)<br>   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)<br>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)<br>   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)<br>   at System.IO.StreamReader..ctor(String path, Encoding encoding)<br>   at Shinta.Common.Deserialize[T](String path, T obj)<br>   at NicoKaraMaker2.Models.AddOns.SettingsAddOn.Load()"
2020/06/28,13:13:01,10896,N12912/M1,NicoKaraMaker2,Error,"アドオン設定読み込み時エラー：<br>Could not find file 'C:\Users\Administrator\AppData\Roaming\SHINTA\NicoKaraMaker2\AddOns\SHINTA.EmptyLineBreaker.config'."
2020/06/28,13:13:01,10896,N12912/M1,NicoKaraMaker2,Status,"　スタックトレース：<br>   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)<br>   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)<br>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)<br>   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)<br>   at System.IO.StreamReader..ctor(String path, Encoding encoding)<br>   at Shinta.Common.Deserialize[T](String path, T obj)<br>   at NicoKaraMaker2.Models.AddOns.SettingsAddOn.Load()"
2020/06/28,13:13:01,10896,N12912/M1,NicoKaraMaker2,Error,"アドオン設定読み込み時エラー：<br>Could not find file 'C:\Users\Administrator\AppData\Roaming\SHINTA\NicoKaraMaker2\AddOns\SHINTA.TopLongAdjuster.config'."
2020/06/28,13:13:01,10896,N12912/M1,NicoKaraMaker2,Status,"　スタックトレース：<br>   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)<br>   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)<br>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)<br>   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)<br>   at System.IO.StreamReader..ctor(String path, Encoding encoding)<br>   at Shinta.Common.Deserialize[T](String path, T obj)<br>   at NicoKaraMaker2.Models.AddOns.SettingsAddOn.Load()"
2020/06/28,13:13:01,10896,N12912/M1,NicoKaraMaker2,Error,"アドオン設定読み込み時エラー：<br>Could not find file 'C:\Users\Administrator\AppData\Roaming\SHINTA\NicoKaraMaker2\AddOns\SHINTA.TopShortAdjuster.config'."
2020/06/28,13:13:01,10896,N12912/M1,NicoKaraMaker2,Status,"　スタックトレース：<br>   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)<br>   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)<br>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)<br>   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)<br>   at System.IO.StreamReader..ctor(String path, Encoding encoding)<br>   at Shinta.Common.Deserialize[T](String path, T obj)<br>   at NicoKaraMaker2.Models.AddOns.SettingsAddOn.Load()"
2020/06/28,13:13:01,10896,N12912/M1,NicoKaraMaker2,Error,"アドオン設定読み込み時エラー：<br>Could not find file 'C:\Users\Administrator\AppData\Roaming\SHINTA\NicoKaraMaker2\AddOns\SHINTA.FadeSelector.config'."
2020/06/28,13:13:01,10896,N12912/M1,NicoKaraMaker2,Status,"　スタックトレース：<br>   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)<br>   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)<br>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)<br>   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)<br>   at System.IO.StreamReader..ctor(String path, Encoding encoding)<br>   at Shinta.Common.Deserialize[T](String path, T obj)<br>   at NicoKaraMaker2.Models.AddOns.SettingsAddOn.Load()"

**Comment by UltimateAmitieKaiNiC** [comment]
スプラッシュウィンドウで突然に自動強制終了じゃないか！

**Comment by shinta0806** [comment]
中国語版 2004 でも動かなかったとのことなので、中国語版では動作しない可能性があります。
本件について現時点ではこれ以上の確認・対策は困難なため、クローズします。

**Comment by UltimateAmitieKaiNiC** [comment]
残念ながら初代のみ使用します…

**Comment by UltimateAmitieKaiNiC** [comment]
GAME OVER

**Comment by UltimateAmitieKaiNiC** [comment]
天皇陛下バンザーイ！！！！！！！！！！！！！

**Comment by shinta0806** [comment]
ここは課題管理のためのスレッドです。
天皇の話や挨拶などは書き込まないようお願いします。

**Comment by UltimateAmitieKaiNiC** [comment]
ごめんよ

**Comment by UltimateAmitieKaiNiC** [comment]
このソフトは私に合わないよぉ~

**Comment by UltimateAmitieKaiNiC** [comment]
> ここは課題管理のためのスレッドです。
> 天皇の話や挨拶などは書き込まないようお願いします。

キーボードクラッシャーの空耳かい！
